# coding: utf-8

"""
    Lethean Server

    Lethean dAppServer

    The version of the OpenAPI document: 3.1.1
    Contact: hello@lt.hn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dappserver-server-sdk.api.apps_api import AppsApi


class TestAppsApi(unittest.TestCase):
    """AppsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppsApi()

    def tearDown(self) -> None:
        pass

    def test_get_market_place_apps(self) -> None:
        """Test case for get_market_place_apps

        """
        pass

    def test_install_app(self) -> None:
        """Test case for install_app

        """
        pass

    def test_list_apps(self) -> None:
        """Test case for list_apps

        """
        pass

    def test_remove_app(self) -> None:
        """Test case for remove_app

        """
        pass


if __name__ == '__main__':
    unittest.main()
