# coding: utf-8

"""
    Lethean Server

    Lethean dAppServer

    The version of the OpenAPI document: 3.1.1
    Contact: hello@lt.hn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dappserver_server_sdk.models.process_kill_dto import ProcessKillDTO

class TestProcessKillDTO(unittest.TestCase):
    """ProcessKillDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessKillDTO:
        """Test ProcessKillDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessKillDTO`
        """
        model = ProcessKillDTO()
        if include_optional:
            return ProcessKillDTO(
                key = ''
            )
        else:
            return ProcessKillDTO(
                key = '',
        )
        """

    def testProcessKillDTO(self):
        """Test ProcessKillDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
