# coding: utf-8

"""
    Lethean Server

    Lethean dAppServer

    The version of the OpenAPI document: 3.1.1
    Contact: hello@lt.hn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dappserver_server_sdk.models.process_run_dto import ProcessRunDTO

class TestProcessRunDTO(unittest.TestCase):
    """ProcessRunDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessRunDTO:
        """Test ProcessRunDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessRunDTO`
        """
        model = ProcessRunDTO()
        if include_optional:
            return ProcessRunDTO(
                command = '',
                args = '',
                options = dappserver_server_sdk.models.process_add_dto.ProcessAddDTO(
                    key = '', 
                    command = '', 
                    std_out = dappserver_server_sdk.models.std_out.stdOut(), 
                    std_in = dappserver_server_sdk.models.std_in.stdIn(), 
                    std_err = dappserver_server_sdk.models.std_err.stdErr(), )
            )
        else:
            return ProcessRunDTO(
                command = '',
                args = '',
                options = dappserver_server_sdk.models.process_add_dto.ProcessAddDTO(
                    key = '', 
                    command = '', 
                    std_out = dappserver_server_sdk.models.std_out.stdOut(), 
                    std_in = dappserver_server_sdk.models.std_in.stdIn(), 
                    std_err = dappserver_server_sdk.models.std_err.stdErr(), ),
        )
        """

    def testProcessRunDTO(self):
        """Test ProcessRunDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
