# coding: utf-8

"""
    Lethean Server

    Lethean dAppServer

    The version of the OpenAPI document: 3.1.1
    Contact: hello@lt.hn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dappserver_server_sdk.models.encrypted_request_dto import EncryptedRequestDTO

class TestEncryptedRequestDTO(unittest.TestCase):
    """EncryptedRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EncryptedRequestDTO:
        """Test EncryptedRequestDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EncryptedRequestDTO`
        """
        model = EncryptedRequestDTO()
        if include_optional:
            return EncryptedRequestDTO(
                payload = '',
                signature = ''
            )
        else:
            return EncryptedRequestDTO(
                payload = '',
        )
        """

    def testEncryptedRequestDTO(self):
        """Test EncryptedRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
