# coding: utf-8

"""
    Lethean Server

    Lethean dAppServer

    The version of the OpenAPI document: 3.1.1
    Contact: hello@lt.hn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dappserver_server_sdk.api.info_api import InfoApi


class TestInfoApi(unittest.TestCase):
    """InfoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InfoApi()

    def tearDown(self) -> None:
        pass

    def test_welcome_page(self) -> None:
        """Test case for welcome_page

        """
        pass


if __name__ == '__main__':
    unittest.main()
