# coding: utf-8

"""
    Lethean Server

    Lethean dAppServer

    The version of the OpenAPI document: 3.1.1
    Contact: hello@lt.hn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dappserver-server-sdk.models.config_object_clear_dto import ConfigObjectClearDTO

class TestConfigObjectClearDTO(unittest.TestCase):
    """ConfigObjectClearDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigObjectClearDTO:
        """Test ConfigObjectClearDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigObjectClearDTO`
        """
        model = ConfigObjectClearDTO()
        if include_optional:
            return ConfigObjectClearDTO(
                group = ''
            )
        else:
            return ConfigObjectClearDTO(
                group = '',
        )
        """

    def testConfigObjectClearDTO(self):
        """Test ConfigObjectClearDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
