# coding: utf-8

"""
    Lethean Server

    Lethean dAppServer

    The version of the OpenAPI document: 3.1.1
    Contact: hello@lt.hn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dappserver-server-sdk.models.create_account_dto import CreateAccountDTO

class TestCreateAccountDTO(unittest.TestCase):
    """CreateAccountDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAccountDTO:
        """Test CreateAccountDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAccountDTO`
        """
        model = CreateAccountDTO()
        if include_optional:
            return CreateAccountDTO(
                username = '',
                password = ''
            )
        else:
            return CreateAccountDTO(
                username = '',
                password = '',
        )
        """

    def testCreateAccountDTO(self):
        """Test CreateAccountDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
