# coding: utf-8

"""
    Lethean Server

    Lethean dAppServer

    The version of the OpenAPI document: 3.1.1
    Contact: hello@lt.hn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dappserver_server_sdk.models.file_download_request import FileDownloadRequest

class TestFileDownloadRequest(unittest.TestCase):
    """FileDownloadRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileDownloadRequest:
        """Test FileDownloadRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileDownloadRequest`
        """
        model = FileDownloadRequest()
        if include_optional:
            return FileDownloadRequest(
                url = '',
                file = '',
                dir = '',
                mode = 1.337
            )
        else:
            return FileDownloadRequest(
                url = '',
                file = '',
                dir = '',
        )
        """

    def testFileDownloadRequest(self):
        """Test FileDownloadRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
