# coding: utf-8

"""
    Lethean Server

    Lethean dAppServer

    The version of the OpenAPI document: 3.1.1
    Contact: hello@lt.hn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dappserver-server-sdk.models.quasi_salt_hash_verify_dto import QuasiSaltHashVerifyDTO

class TestQuasiSaltHashVerifyDTO(unittest.TestCase):
    """QuasiSaltHashVerifyDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuasiSaltHashVerifyDTO:
        """Test QuasiSaltHashVerifyDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuasiSaltHashVerifyDTO`
        """
        model = QuasiSaltHashVerifyDTO()
        if include_optional:
            return QuasiSaltHashVerifyDTO(
                input = '',
                hash = ''
            )
        else:
            return QuasiSaltHashVerifyDTO(
                input = '',
                hash = '',
        )
        """

    def testQuasiSaltHashVerifyDTO(self):
        """Test QuasiSaltHashVerifyDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
