# coding: utf-8

"""
    Lethean Server

    Lethean dAppServer

    The version of the OpenAPI document: 3.1.1
    Contact: hello@lt.hn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dappserver_server_sdk.api.config_api import ConfigApi


class TestConfigApi(unittest.TestCase):
    """ConfigApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigApi()

    def tearDown(self) -> None:
        pass

    def test_clear_config(self) -> None:
        """Test case for clear_config

        """
        pass

    def test_count_config(self) -> None:
        """Test case for count_config

        """
        pass

    def test_get_config(self) -> None:
        """Test case for get_config

        """
        pass

    def test_load(self) -> None:
        """Test case for load

        """
        pass

    def test_parse(self) -> None:
        """Test case for parse

        """
        pass

    def test_remove_config(self) -> None:
        """Test case for remove_config

        """
        pass

    def test_render(self) -> None:
        """Test case for render

        """
        pass

    def test_render_and_load(self) -> None:
        """Test case for render_and_load

        """
        pass

    def test_render_string(self) -> None:
        """Test case for render_string

        """
        pass

    def test_set_config(self) -> None:
        """Test case for set_config

        """
        pass


if __name__ == '__main__':
    unittest.main()
