# coding: utf-8

"""
    Lethean Server

    Lethean dAppServer

    The version of the OpenAPI document: 3.1.1
    Contact: hello@lt.hn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dappserver-server-sdk.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        """
        pass

    def test_login(self) -> None:
        """Test case for login

        """
        pass


if __name__ == '__main__':
    unittest.main()
