# coding: utf-8

"""
    Lethean Server

    Lethean dAppServer

    The version of the OpenAPI document: 3.1.1
    Contact: hello@lt.hn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dappserver-server-sdk.api.blockchain_api import BlockchainApi


class TestBlockchainApi(unittest.TestCase):
    """BlockchainApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BlockchainApi()

    def tearDown(self) -> None:
        pass

    def test_download_daemon(self) -> None:
        """Test case for download_daemon

        """
        pass

    def test_export_blockchain(self) -> None:
        """Test case for export_blockchain

        """
        pass

    def test_import_blockchain(self) -> None:
        """Test case for import_blockchain

        """
        pass

    def test_json_rpc(self) -> None:
        """Test case for json_rpc

        """
        pass

    def test_start_daemon(self) -> None:
        """Test case for start_daemon

        """
        pass

    def test_start_wallet(self) -> None:
        """Test case for start_wallet

        """
        pass

    def test_wallet_json_rpc(self) -> None:
        """Test case for wallet_json_rpc

        """
        pass


if __name__ == '__main__':
    unittest.main()
