# coding: utf-8

"""
    Lethean Server

    Lethean dAppServer

    The version of the OpenAPI document: 3.1.1
    Contact: hello@lt.hn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dappserver-server-sdk.api.cryptography_api import CryptographyApi


class TestCryptographyApi(unittest.TestCase):
    """CryptographyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CryptographyApi()

    def tearDown(self) -> None:
        pass

    def test_create_quasi_salt(self) -> None:
        """Test case for create_quasi_salt

        """
        pass

    def test_decrypt(self) -> None:
        """Test case for decrypt

        """
        pass

    def test_encrypt(self) -> None:
        """Test case for encrypt

        """
        pass

    def test_generate_key_pair(self) -> None:
        """Test case for generate_key_pair

        """
        pass

    def test_get_public_key(self) -> None:
        """Test case for get_public_key

        """
        pass

    def test_sha256(self) -> None:
        """Test case for sha256

        """
        pass

    def test_sha384(self) -> None:
        """Test case for sha384

        """
        pass

    def test_sha512(self) -> None:
        """Test case for sha512

        """
        pass

    def test_sign(self) -> None:
        """Test case for sign

        """
        pass

    def test_verify(self) -> None:
        """Test case for verify

        """
        pass

    def test_verify_quasi_salt(self) -> None:
        """Test case for verify_quasi_salt

        """
        pass


if __name__ == '__main__':
    unittest.main()
